name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1
      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Build with Gradle
        run: ./gradlew clean check --stacktrace
      - name: Upload snapshot (main only)
        if: success() && github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: '${{ secrets.SONATYPEUSERNAME }}'
          ORG_GRADLE_PROJECT_mavenCentralPassword: '${{ secrets.SONATYPEPASSWORD }}'
